name: Get Runner IP Address
description: Action to get the public IP address of the GitHub runner, will retry for MAX_TRIES if it fails to get a valid IP address, with exponential backoff between attempts.

outputs:
  ip_address:
    description: The public IP address of the GitHub runner
    value: ${{ steps.get_ip.outputs.ip_address }}

runs:
  using: composite
  steps:
    - name: Get Public IP Address of GitHub Runner 
      id: get_ip
      shell: bash
      run: |
        MAX_TRIES=3
        DELAY=1
        for TRY in $(seq $MAX_TRIES); do
          IP=$(curl -s https://api.ipify.org/)
          if [[ $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "ip_address=$IP" >> $GITHUB_OUTPUT
            echo "GitHub Runner IP: $IP"
            exit 0
          else
            echo "Attempt $TRY: Failed to get valid IP address. Retrying in $DELAY seconds..."
            sleep $DELAY
            DELAY=$((DELAY * 2))
          fi
        done
        echo "Failed to get valid IP address after $MAX_TRIES attempts."
        exit 1
