name: Contentful Schema Migrate

on:
  workflow_dispatch:
    inputs:
      target_environment:
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target_environment }}

    outputs:
      staging-environment: ${{ steps.staging-env.outputs.staging-environment }}
      required-migrations: ${{ steps.required-migrations.outputs.required-migrations }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install jq (JSON processor)
        run: sudo apt-get install -y jq

      - name: Read settings.json and export environment variables
        run: |
          SETTINGS_PATH="$(pwd)/settings.json"
          echo "SETTINGS_PATH=$SETTINGS_PATH" >> $GITHUB_ENV

          SPACE_ID=$(jq -r '.ContentfulOptions.SpaceId' $SETTINGS_PATH)
          MANAGEMENT_TOKEN=$(jq -r '.ContentfulOptions.ManagementToken' $SETTINGS_PATH)
          ENV_ID="${{ inputs.target_environment }}" # Use environment selected in GitHub Actions input

          echo "SPACE_ID=$SPACE_ID" >> $GITHUB_ENV
          echo "MANAGEMENT_TOKEN=$MANAGEMENT_TOKEN" >> $GITHUB_ENV
          echo "ENV_ID=$ENV_ID" >> $GITHUB_ENV

          if [[ -z "$SPACE_ID" || -z "$MANAGEMENT_TOKEN" ]]; then
            echo "Error: Required values missing in settings.json"
            exit 1
          fi

      - name: Install npm packages
        working-directory: ./contentful
        run: npm ci

      - name: Get target environment current migration version
        id: current-migration-version
        working-directory: ./Contentful-Schema/utils
        run: node get-environment-version.js

      - name: Determine timestamp for new staging environment
        run: echo "TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)" >> $GITHUB_ENV

      - name: Set var for name of new environment
        id: staging-env
        run: echo "staging-environment=$(echo ${{ inputs.target_environment }}-${{ env.TIMESTAMP }})" >> $GITHUB_OUTPUT

  migrate:
    if: ${{ join(needs.setup.outputs.required-migrations, '') != '[]' }}
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.required-migrations) }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Read settings.json and export environment variables
        run: |
          SETTINGS_PATH="$(pwd)/settings.json"
          echo "SETTINGS_PATH=$SETTINGS_PATH" >> $GITHUB_ENV

          SPACE_ID=$(jq -r '.ContentfulOptions.SpaceId' $SETTINGS_PATH)
          MANAGEMENT_TOKEN=$(jq -r '.ContentfulOptions.ManagementToken' $SETTINGS_PATH)
          ENV_ID="${{ inputs.target_environment }}" # Use environment selected in GitHub Actions input

          echo "SPACE_ID=$SPACE_ID" >> $GITHUB_ENV
          echo "MANAGEMENT_TOKEN=$MANAGEMENT_TOKEN" >> $GITHUB_ENV
          echo "ENV_ID=$ENV_ID" >> $GITHUB_ENV

          if [[ -z "$SPACE_ID" || -z "$MANAGEMENT_TOKEN" ]]; then
            echo "Error: Required values missing in settings.json"
            exit 1
          fi

      - name: Install npm packages
        working-directory: ./Contentful-Schema
        run: npm ci

      - name: Install Contentful CLI
        run: npm install -g contentful-cli

      - name: Run migration script ${{ matrix.value }}
        working-directory: ./Contentful-Schema/migrations
        run: contentful space migration --space-id "${{ env.SPACE_ID }}" --environment-id "${{ env.ENV_ID }}" --management-token "${{ env.MANAGEMENT_TOKEN }}" ${{ matrix.value }} --yes
