receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:${SPLUNK_PORT}"

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch:
    send_batch_size: 10000
    timeout: 2s
  resource:
    attributes:
      - key: service.name
        value: "${OTEL_SERVICE_NAME}"
        action: insert

exporters:
  debug:
    verbosity: detailed

  otlphttp/splunk:
    endpoint: "https://ingest.${SPLUNK_REALM}.observability.splunkcloud.com"
    tls:
      insecure: false
    headers:
      "X-SF-Token": "${SPLUNK_ACCESS_TOKEN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/splunk]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/splunk]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/splunk]