FROM node:24-alpine3.24

RUN npm install -g --ignore-scripts contentful-cli@4.0.2

WORKDIR /opt/backup

RUN adduser -D nonroot
USER nonroot

#ENTRYPOINT ["sh", "-c", "contentful space export --management-token $token --space-id=$space --environment-id=$envid"]
ENTRYPOINT ["contentful", "space export"]