FROM node:24-alpine3.24

RUN npm install -g --ignore-scripts contentful-cli@4.0.2

WORKDIR /opt/backup

RUN adduser -D nonroot
USER nonroot

#ENTRYPOINT ["sh", "-c", "contentful space import --management-token $token --space-id=$space --environment-id=$envid --content-file /opt/backup/prod-contentful-backup-output.json"]
ENTRYPOINT ["contentful", "space", "import"]