FROM node:24-alpine3.24

RUN npm install -g contentful-cli

WORKDIR /opt/backup

RUN useradd -m nonroot
USER nonroot

#ENTRYPOINT ["sh", "-c", "contentful space export --management-token $token --space-id=$space --environment-id=$envid"]
ENTRYPOINT ["contentful", "space export"]