name: 'care-leavers'
services:
  care-leavers-web:
    build:
      context: ../../
      dockerfile: web/CareLeavers.Web/Dockerfile
    ports:
      - "7050:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: EndToEnd
      Caching__Type: "None"
      ContentfulOptions__DeliveryApiKey: ${CONTENTFUL_DELIVERY_API_KEY}
      ContentfulOptions__PreviewApiKey: ${CONTENTFUL_PREVIEW_API_KEY}
      ContentfulOptions__SpaceId: ${CONTENTFUL_SPACE_ID}
      ContentfulOptions__Environment: 'e2e'