name: 'care-leavers'
services:
  care-leavers-web:
    image: care-leavers-web:staging
    ports:
      - "7050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - Caching__Type=Memory
      - ContentfulOptions__DeliveryApiKey=${CONTENTFUL_DELIVERY_API_KEY}
      - ContentfulOptions__PreviewApiKey=${CONTENTFUL_PREVIEW_API_KEY}
      - ContentfulOptions__SpaceId=${CONTENTFUL_SPACE_ID}
      - ContentfulOptions__Environment=production
      - Rebrand=true
      - ASPNETCORE_URLS=https://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=staging
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro