name: 'care-leavers'
services:
  care-leavers-web:
    build:
      context: ../../
      dockerfile: web/CareLeavers.Web/Dockerfile
      tags:
        - care-leavers-web:dev
    ports:
      - "7050:8080"