name: Contentful Migrations

on:
  workflow_dispatch:
    inputs:
      target_environment:
        required: true
        description: 'Contentful environment to deploy to'
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  contentful:
    runs-on: ubuntu-latest

    steps:
      - name: Install Contentful CLI
        run: npm install -g contentful-cli

      - name: Login to Contentful with management token
        run: contentful login --management-token "${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}"