name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to deploy to"
        required: true
        default: "elz-test"
        options:
          - "elz-test"
          - "elz-staging"
          - "elz-production"

run-name: ${{ github.event_name == 'push' && 'Deploy to Test' || format('Deploy to {0}', github.event.inputs.environment) }}

concurrency:
  group: "${{ github.workflow }}-${{ github.event_name == 'push' && 'elz-test' || github.event.inputs.environment }}"
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write
  packages: write

env:
  TAG_NAME: "${{ github.sha }}"
  ENVIRONMENT_PREFIX: "s272${{ vars.ENVIRONMENT_PREFIX}}"

jobs:
  package:
    name: Package Web in Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Lowercase Repository Name
        id: lowercase
        uses: ./.github/actions/lowercase
        with:
          value: ${{ github.repository }}
        
      - name: Build Web Docker Image
        run: |
          docker build . -t ghcr.io/${{ steps.lowercase.outputs.lowercased_value }}:${{ env.TAG_NAME }} -f web/CareLeavers.Web/Dockerfile
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push Web Docker Image
        run: |
          docker push ghcr.io/${{ steps.lowercase.outputs.lowercased_value }}:${{ env.TAG_NAME }}

  deploy:
    name: Deploying to ${{ github.event_name == 'push' && 'elz-test' || github.event.inputs.environment }}
    needs: [package]
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && 'elz-test' || github.event.inputs.environment }}
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.10.4
          terraform_wrapper: false

      - name: Azure CLI Login
        uses: azure/login@v3
        with:
          creds: |
            {
                "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
                "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
                "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }
      
      - name: Add Alert Management Provider
        run: |
          az provider register --namespace Microsoft.AlertsManagement

      - name: Lowercase Repository Name
        id: lowercase
        uses: ./.github/actions/lowercase
        with:
          value: ${{ github.repository }}

      - name: Unlock Terraform State
        id: terraform_unlock
        uses: ./.github/actions/manage-storage-network-access
        with:
          storage_account_name: ${{ env.ENVIRONMENT_PREFIX }}cltfstate
          resource_group_name: ${{ env.ENVIRONMENT_PREFIX }}rg-uks-cl-tfstate
          enable_network_access: true
      
      - name: Terraform Init
        id: terraform_init
        working-directory: ./src/infrastructure/terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ env.ENVIRONMENT_PREFIX }}rg-uks-cl-tfstate" \
            -backend-config="storage_account_name=${{ env.ENVIRONMENT_PREFIX }}cltfstate" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Plan
        id: terraform_plan
        working-directory: ./src/infrastructure/terraform
        run: |
          terraform plan -out plan.plan
        env:
          TF_VAR_aspnetcore_environment: ${{ vars.ELZ_ENVIRONMENT }}
          TF_VAR_environment_prefix: ${{ vars.ENVIRONMENT_PREFIX }}
          TF_VAR_elz_environment: ${{ vars.ENVIRONMENT_TAG }}
          TF_VAR_contentful_delivery_api_key: ${{ secrets.CONTENTFUL_DELIVERY_API_KEY }}
          TF_VAR_contentful_preview_api_key: ${{ secrets.CONTENTFUL_PREVIEW_API_KEY }}
          TF_VAR_contentful_management_api_key: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
          TF_VAR_contentful_space_id: ${{ secrets.CONTENTFUL_SPACE_ID }}
          TF_VAR_contentful_environment: ${{ vars.CONTENTFUL_ENVIRONMENT }}
          TF_VAR_contentful_use_preview_api: ${{ vars.CONTENTFUL_PREVIEW }}
          TF_VAR_caching_type: ${{ vars.CACHING_TYPE }}
          TF_VAR_scripts_clarity: ${{ vars.SCRIPTS_CLARITY }}
          TF_VAR_custom_domain: ${{ vars.CUSTOM_DOMAIN }}
          TF_VAR_azure_frontdoor_scale: ${{ vars.AZURE_FRONTDOOR_SCALE }}
          TF_VAR_pdf_generation_api_key: ${{ secrets.PDF_GENERATION_API_KEY }}
          TF_VAR_pdf_generation_use_sandbox: ${{ vars.PDF_GENERATION_USE_SANDBOX }}
          TF_VAR_rebrand: ${{ vars.REBRAND }}
          TF_VAR_support_alert_email: ${{ secrets.SUPPORT_ALERT_EMAIL }}
          TF_VAR_gtaa_base_url: ${{ vars.GTAA_BASE_URL }}
      
      - name: Terraform Apply
        id: terraform_apply
        working-directory: ./src/infrastructure/terraform
        run: |
          terraform apply plan.plan

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "${{ env.ENVIRONMENT_PREFIX }}-uks-cl-web-app-service"
          slot-name: "${{vars.WEB_APP_SLOT}}"
          images: "ghcr.io/${{ steps.lowercase.outputs.lowercased_value }}:${{ env.TAG_NAME }}"
      
      - name: Swap Slot to Production
        if: github.event.inputs.environment == 'elz-production'
        run: |
          az webapp deployment slot swap --name ${{ env.ENVIRONMENT_PREFIX }}-uks-cl-web-app-service --resource-group ${{ env.ENVIRONMENT_PREFIX }}rg-uks-cl-web --slot staging --target-slot production

      - name: Delete Staging Slot
        if: github.event.inputs.environment == 'elz-production' 
        run: |
          az webapp deployment slot delete --name ${{ env.ENVIRONMENT_PREFIX }}-uks-cl-web-app-service --resource-group ${{ env.ENVIRONMENT_PREFIX }}rg-uks-cl-web --slot staging 
      
      - name: Lock Terraform State
        if: ${{ always() }}
        id: terraform_lock
        uses: ./.github/actions/manage-storage-network-access
        with:
          storage_account_name: ${{ env.ENVIRONMENT_PREFIX }}cltfstate
          resource_group_name: ${{ env.ENVIRONMENT_PREFIX }}rg-uks-cl-tfstate
          enable_network_access: false

      - name: Clear Cache
        shell: bash
        run: |
          curl -X POST "https://${{ vars.CUSTOM_DOMAIN }}/b0e0dce2-b96d-4b94-a800-63c3ab56e72f"