name: Deploy with Tag

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to deploy to"
        required: true
        default: "elz-test"
        options:
          - "elz-test"
          - "elz-staging"
          - "elz-production"

run-name: ${{ format('Deploy to {0}', github.event.inputs.environment) }}

permissions: {}

concurrency:
  group: "deploy-${{ github.event.inputs.environment }}"
  cancel-in-progress: false

env:
  TAG_NAME: "${{ github.ref_name }}"
  ENVIRONMENT_PREFIX: "s272${{ vars.ENVIRONMENT_PREFIX }}"

jobs:
  validate_using_tag:
    name: Validating the workflow is using a tag for deployment
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Run Validation
        uses: ./.github/actions/validate-deploy
        with:
          deploy: "tag"

  deploy:
    name: Deploying to ${{ github.event.inputs.environment }}
    needs: [validate_using_tag]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Run Deploy Action
        uses: ./.github/actions/deploy
        with:
          environment: ${{ github.event.inputs.environment }}
          webapp_slot: ${{ vars.WEB_APP_SLOT }}
          custom_domain: ${{ vars.CUSTOM_DOMAIN }}
          environment_prefix: ${{ env.ENVIRONMENT_PREFIX }}
          tag_name: ${{ env.TAG_NAME }}
          AZURE_CLIENT_ID_SECRET: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_SUBSCRIPTION_ID_SECRET: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID_SECRET: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          CONTENTFUL_DELIVERY_API_KEY_SECRET: ${{ secrets.CONTENTFUL_DELIVERY_API_KEY }}
          CONTENTFUL_PREVIEW_API_KEY_SECRET: ${{ secrets.CONTENTFUL_PREVIEW_API_KEY }}
          CONTENTFUL_MANAGEMENT_TOKEN_SECRET: ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}
          CONTENTFUL_SPACE_ID_SECRET: ${{ secrets.CONTENTFUL_SPACE_ID }}
          SUPPORT_ALERT_EMAIL_SECRET: ${{ secrets.SUPPORT_ALERT_EMAIL }}
          BASIC_AUTH_CREDS_SECRET: ${{ secrets.BASIC_AUTH_CREDS }}
