name: Generate - Zap Scan

on:
  workflow_dispatch:
    inputs:
      environment_prefix:
        description: 'Environment Prefix'
        required: true
        default: 'd01'
        options:
          - 'd01'
jobs:
  zap_scan:
    name: 'Run Zap Scan'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://s186${{ github.event.inputs.environment_prefix }}-cl-web-fd.azurefd.net'
          rules_file_name: 'src/rules.tsv'
          cmd_options: '-a'
          allow_issue_writing: 'false'

      - name: Commit and Push Report
        run: |
          mv report_md.md docs/testing/Security-Scan-Report.md
          git add docs/testing/Security-Scan-Report.md
          git config --global user.name "Documentation Bot"
          git config --global user.email "documentation-bot-bot@users.noreply.github.com"
          git commit -am "Generated zap scan report"
          git push
        continue-on-error: true