name: Generate - Contentful Backup

on:
  workflow_dispatch:

  schedule:
    - cron: "0 23 * * 1-5"

permissions: {}

run-name: Running backup procedure of Contentful space
jobs:
  backup-contentful:
    name: "Create backup"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: 'elz-test'
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
      ENVIRONMENT_PREFIX: "s272${{ vars.ENVIRONMENT_PREFIX}}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: "Az CLI login"
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43
        with:
          creds: |
            {
                "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
                "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
                "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      - name: Build and Run Docker Backup Container
        run: |
          mkdir -p ./backups

          chmod 777 ./backups
          
          docker build -f src/contentful/Utilities/Dockerfile.backup -t contentful-backup-tool .
          
          docker run \
            -v ${{ github.workspace }}/backups:/output \
            contentful-backup-tool \
              --space-id "${{ secrets.CONTENTFUL_SPACE_ID }}" \
              --management-token "${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }}" \
              --environment-id "production" \
              --export-dir "/output" \
              --content-file "export.json"

      - name: Unlock Web Storage Account
        id: storage_unlock
        uses: ./.github/actions/manage-storage-network-access
        with:
          storage_account_name: ${{ env.ENVIRONMENT_PREFIX }}webstorage
          resource_group_name: ${{ env.ENVIRONMENT_PREFIX }}rg-uks-cl-web
          enable_network_access: true

      - name: Upload backup file to blob storage
        uses: azure/CLI@9eb25b8360668fb0ecbafa808d40e2197b2f5f52
        with:
          inlineScript: |
            BACKUP_DATE=$(date +%Y-%m-%d)

            CONN_STR=$(az keyvault secret show \
              --name "blob-storage-connection-string" \
              --vault-name "${ENVIRONMENT_PREFIX}-kv-uks-cl" \
              --query "value" \
              --output tsv)

            echo "::add-mask::$CONN_STR"

            az storage blob upload \
              --connection-string "$CONN_STR" \
              --container-name "${ENVIRONMENT_PREFIX}-backup-container" \
              --file ./backups/export.json \
              --name "contentful-backup-${BACKUP_DATE}-run-${{ github.run_id }}.json"
        env:
          ENVIRONMENT_PREFIX: ${{ env.ENVIRONMENT_PREFIX }}  

      - name: Lock Web Storage Account
        if: ${{ always() }}
        id: storage_lock
        uses: ./.github/actions/manage-storage-network-access
        with:
          storage_account_name: ${{ env.ENVIRONMENT_PREFIX }}webstorage
          resource_group_name: ${{ env.ENVIRONMENT_PREFIX }}rg-uks-cl-web
          enable_network_access: false