name: Manual Trigger Test

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Test message'
        required: true
        default: 'Hello World'

jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "${{ github.event.inputs.message }}"