name: Validate - Web

on:
  workflow_call:
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    name: 'Build Web'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3

      - name: Setup Node.JS
        uses: actions/setup-node@v6
        with:
          node-version: "26"

      - name: Validate Frontend Build System
        working-directory: ./src/web/CareLeavers.Web.Node
        run: |
          npm ci --ignore-scripts --omit=dev
          npm run build

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            src/**/packages.lock.json

      - name: Restore dependencies
        working-directory: ./src
        run: dotnet restore --locked-mode

      - name: Build Solution
        working-directory: ./src
        run: dotnet build --no-restore

      - name: Run Integration Tests
        working-directory: ./src
        run: dotnet test --no-build --verbosity normal