name: Validate - SonarQube

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: read

env:
  DOTNET_VERSION: '8.x'
  JAVA_VERSION: '21'

jobs:
  build-test-analyse:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Build, Test & Analyse
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: './src'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-quality: 'ga'

      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          distribution: "microsoft"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Install Sonar Scanner
        shell: bash
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          dotnet tool install --global dotnet-sonarscanner

      - name: Start Sonar Scanner
        shell: bash
        run: |
          dotnet-sonarscanner begin \
          /o:"dfe-digital" \
          /k:"DFE-Digital_care-leavers" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.coverage.exclusions=**/Program.cs,**/LoggingConfigurationExtensions.cs,**.cshtml,**/Configuration/**,**/e2e/**,**/contentful/Synchronisation/**,**/utilities/**,**/Migrations/** \
          /d:sonar.exclusions=**/Program.cs,**/LoggingConfigurationExtensions.cs,**/Migrations/** \
          /d:sonar.scanner.skipJreProvisioning=true \
          /s:${{ github.workspace }}/SonarQube.Analysis.xml

      - name: Restore Solution
        shell: bash
        run: dotnet restore

      - name: Build Solution
        shell: bash
        run: |
          dotnet build \
          --configuration Release \
          --no-restore

      - name: Test Solution
        shell: bash
        run: |
          dotnet test \
          --configuration Release \
          --no-restore \
          --no-build \
          --collect "XPlat Code Coverage" \
          --logger "trx;LogFileName=TestResults.trx" \

      - name: Generate Sonar Coverage Report
        if: ${{ success() }}
        run: |
          reportgenerator \
            -reports:./**/coverage.cobertura.xml \
            -targetdir:./CoverageReport \
            -reporttypes:SonarQube \
            -sourcedirs:. \
            -filefilters:"-*/RegexGenerator.g.cs"

      - name: Stop Sonar Scanner
        if: ${{ always() }}
        shell: bash
        run: |
          dotnet-sonarscanner end \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Generate Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: .NET Test Results
          path: "**/*.trx"
          reporter: 'dotnet-trx'