name: Validate - E2E Tests

on:
  push:
    branches: ["main"]
    paths:
      - "src/web/**"
      - "src/e2e/CareLeavers.E2ETests/**"
      - ".github/workflows/validate-web.yaml"
      - ".github/workflows/validate-e2e.yaml"
  pull_request:
    branches: ["main"]
    
permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Playwright Tests    
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5]
        shardTotal: [5]        
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: "24"

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Create Local Developer Certificate
        run: |
          mkdir -p ${HOME}/.aspnet/https
          export SSL_CERT_DIR="$HOME/.aspnet/dev-certs/trust:$SSL_CERT_DIR"
          dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.pfx -p "e2e"
          dotnet dev-certs https --trust
          chmod -R 755 ${HOME}/.aspnet

      - name: Build Web Docker Image
        id: build
        working-directory: ./src
        run: docker build . -t care-leavers-web:e2e -f web/CareLeavers.Web/Dockerfile

      - name: Run E2E Docker Image
        id: run
        if: steps.build.outcome == 'success'
        working-directory: ./src
        run: |
          docker compose -f infrastructure/docker/docker-compose-ci.yml up -d
        env:
          CONTENTFUL_DELIVERY_API_KEY: ${{ secrets.CONTENTFUL_DELIVERY_API_KEY }}
          CONTENTFUL_PREVIEW_API_KEY: ${{ secrets.CONTENTFUL_PREVIEW_API_KEY }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}

      - name: Install dependencies
        working-directory: ./src/e2e/CareLeavers.E2ETests
        run: yarn install --immutable --immutable-cache

      - name: Install Playwright Browsers
        working-directory: ./src/e2e/CareLeavers.E2ETests       
        run: yarn playwright install --with-deps     

      - name: Run Playwright Tests - ${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        if: steps.run.outcome == 'success'
        working-directory: ./src/e2e/CareLeavers.E2ETests
        run: yarn playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} -c playwright-ci.config.ts

      - name: Upload Playwright Test Report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:        
          name: playwright-report-${{ matrix.shardIndex }}
          path: ./src/e2e/CareLeavers.E2ETests/playwright-report/
          if-no-files-found: ignore

      - name: Upload Screenshots on Failure
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: playwright-screenshots
          path: ./src/e2e/CareLeavers.E2ETests/test-results/screenshots/

  merge-report:
    runs-on: ubuntu-latest
    name: Download & Merge Reports
    if: ${{ !cancelled() }}
    needs: test
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: "24"

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Create Local Developer Certificate
        run: |
          mkdir -p ${HOME}/.aspnet/https
          export SSL_CERT_DIR="$HOME/.aspnet/dev-certs/trust:$SSL_CERT_DIR"
          dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.pfx -p "e2e"
          dotnet dev-certs https --trust
          chmod -R 755 ${HOME}/.aspnet

      - name: Build Web Docker Image
        id: build
        working-directory: ./src
        run: docker build . -t care-leavers-web:e2e -f web/CareLeavers.Web/Dockerfile

      - name: Run E2E Docker Image
        id: run
        if: steps.build.outcome == 'success'
        working-directory: ./src
        run: |
          docker compose -f infrastructure/docker/docker-compose-ci.yml up -d
        env:
          CONTENTFUL_DELIVERY_API_KEY: ${{ secrets.CONTENTFUL_DELIVERY_API_KEY }}
          CONTENTFUL_PREVIEW_API_KEY: ${{ secrets.CONTENTFUL_PREVIEW_API_KEY }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}

      - name: Install dependencies
        working-directory: ./src/e2e/CareLeavers.E2ETests
        run: yarn install --immutable --immutable-cache   
        
      - name: Install Playwright Browsers
        working-directory: ./src/e2e/CareLeavers.E2ETests       
        run: yarn playwright install --with-deps     

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c 
        with:
         path: ./src/e2e/CareLeavers.E2ETests/playwright-report/
         pattern: playwright-report-*
         merge-multiple: true

      - name: Merge into HTML Report
        run: yarn playwright merge-reports --reporter html ./playwright-report

      - name: Upload HTML report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
         name: html-report--attempt-${{ github.run_attempt }}
         path: playwright-report
         retention-days: 14


      # - name: Download all Playwright report artifacts
      #   uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c 
      #   with:
      #     path: playwright-report
      #     pattern: playwright-report*
      #     merge-multiple: true             
      
      # - name: Assemble merged report 
      #   working-directory: ./src/e2e/CareLeavers.E2ETests
      #   run: |
      #     set -euo pipefail
      #     ARTIFACTS_DIR="$(pwd)/playwright-report/"
      #     echo "Looking for artifacts in $ARTIFACTS_DIR"
      #     if [ ! -d "$ARTIFACTS_DIR" ] || [ -z "$(ls -A "$ARTIFACTS_DIR" || true)" ]; then
      #       echo "No artifacts downloaded at $ARTIFACTS_DIR" >&2
      #       exit 1
      #     fi

      #     echo "Listing downloaded artifacts from playwright-report directory"
      #     ls -la "$ARTIFACTS_DIR" || true

      #     # Find any extracted playwright-report directories under the artifacts folder
      #     REPORT_DIRS=$(find "$ARTIFACTS_DIR" -type d -name 'playwright-report' -print || true)
      #     if [ -z "$REPORT_DIRS" ]; then
      #       echo "No playwright-report directories found under $ARTIFACTS_DIR" >&2
      #       exit 1
      #     fi

      #     # Merge all found reports
      #     echo "Merging reports from: $REPORT_DIRS"
      #     yarn playwright merge-reports $REPORT_DIRS --reporter=html

      # - name: Upload merged Playwright report
      #   uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      #   with:
      #     name: playwright-report-merged
      #     path: ./src/e2e/CareLeavers.E2ETests/artifacts
      #     if-no-files-found: ignore
      #     retention-days: 14
