name: Validate - Zap Scan

on:
  push:
    branches: [ "main", "feat/zap" ]
  workflow_dispatch:
    inputs:
      environment_prefix:
        description: 'Environment Prefix'
        required: true
        default: 'd01'
        options:
          - 'd01'
jobs:
  accessibility_scan:
    name: 'Run Zap Scan'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
#          target: 'https://s186${{ github.event.inputs.environment_prefix }}-cl-web-fd.azurefd.net'
          target: 'https://s186d01-cl-web-fd.azurefd.net'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'