name: Validate - Accessibility

on:
  workflow_dispatch:
    inputs:
      domain_prefix:
        type: choice
        description: "Domain prefix to run against"
        required: true
        default: "test"
        options:
          - "test"
          - "staging"
          - "www"

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      target_env: ${{ steps.map.outputs.env_name }}
    steps:
      - id: map
        run: |
          if [ "${{ github.event.inputs.domain_prefix }}" == "www" ]; then
            echo "env_name=elz-production" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.domain_prefix }}" == "test" ]; then
            echo "env_name=elz-test" >> $GITHUB_OUTPUT
          else
            echo "env_name=elz-staging" >> $GITHUB_OUTPUT
          fi

  accessibility-scan:
    name: "Run Pa11y Accessibility Scan"
    needs: set-env
    runs-on: ubuntu-24.04
    environment: ${{ needs.set-env.outputs.target_env }}
    env:
      BA_CREDS: ${{ secrets.BASIC_AUTH_CREDS }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.JS
        uses: actions/setup-node@v6
        with:
          node-version: "lts/Krypton"

      - name: Run Accessibility Scan
        working-directory: ./src/e2e/pa11y
        run: |
          yarn install --production=true

          cp pa11y.json temp-pa11y.json

          if [ "${{ github.event.inputs.domain_prefix }}" != "www" ]; then
            # jq --arg auth "$BA_CREDS" '.defaults.headers = {"Authorization": $auth}' pa11y.json > temp-pa11y.json
            RAW_USER_PASS=$(echo "$BA_CREDS" | sed 's/Basic //g' | base64 -d)
            SITEMAP_URL="https://${RAW_USER_PASS}@${{ github.event.inputs.domain_prefix }}.support-for-care-leavers.education.gov.uk/sitemap.xml"
          else
            SITEMAP_URL="https://www.support-for-care-leavers.education.gov.uk/sitemap.xml"
          fi

          yarn pa11y-ci --config temp-pa11y.json --sitemap "$SITEMAP_URL"
