name: Link Validation Check

on:
  workflow_dispatch:
  schedule:
    - cron: "00 02 * * 1-5"
      
permissions: {}

jobs:
  scan-website-links:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
    environment: elz-test
    env:
      WEBSITE_ROOT: ${{ vars.APP_WEBSITE_ROOT }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: "./src/utilities/package-lock.json"

      - name: Install npm packages used by util scripts
        working-directory: ./src/utilities
        run: npm ci --ignore-scripts

      - name: Scan for broken links
        working-directory: ./src/utilities
        run: |
          if [ -z "$WEBSITE_ROOT" ]; then
            echo "Error: WEBSITE_ROOT is not set."
            exit 1
          fi
          node scan-website-links.js
