name: Validate - Deployment

on:
  workflow_dispatch:
    inputs:
      environment_prefix:
        description: 'Environment Prefix'
        required: true
        default: 'd01'
        options:
          - 'd01'
jobs:
  accessibility_scan:
    name: 'Run Pa11y Accessibility Scan'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
          dir: ./src/e2e/pa11y

      - name: Run accessibility scans
        working-directory: ./src/e2e/pa11y
        run: yarn pa11y-ci --sitemap https://s186${{ github.event.inputs.environment_prefix }}-cl-web-fd.azurefd.net/sitemap.xml