name: Validate - Accessibility

on:
  workflow_dispatch:
    inputs:
      domain_prefix:
        type: choice
        description: "Domain prefix to run against"
        required: true
        default: "test"
        options:
          - "test"
          - "staging"
          - "www"

jobs:
  accessibility-scan:
    name: "Run Pa11y Accessibility Scan"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.JS
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version: "lts/Krypton"

      - name: Run Accessibility Scan
        working-directory: ./src/e2e/pa11y
        run: |
          yarn install --immutable --immutable-cache --production=true
          yarn pa11y-ci --config pa11y.json --sitemap https://${DOMAIN_PREFIX}.support-for-care-leavers.education.gov.uk/sitemap.xml
        env:
          DOMAIN_PREFIX: ${{ github.event.inputs.domain_prefix }}
