name: Validate - Accessibility

on:
  workflow_dispatch:
    inputs:
      domain_prefix:
        type: choice
        description: "Domain prefix to run against"
        required: true
        default: "test"
        options:
          - "test"
          - "staging"
          - "www"

permissions: {}

jobs:
  accessibility-scan:
    name: "Run Pa11y Accessibility Scan"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Setup Node.JS
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: "lts/Krypton"

      - name: Run Accessibility Scan
        working-directory: ./src/e2e/pa11y
        run: |
          yarn install --immutable --immutable-cache --production=true
          yarn pa11y-ci --config pa11y.json --sitemap https://${DOMAIN_PREFIX}.support-for-care-leavers.education.gov.uk/sitemap.xml
        env:
          DOMAIN_PREFIX: ${{ github.event.inputs.domain_prefix }}
