name: Playwright Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Playwright Tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run Docker Compose
        working-directory: ./src
        env:
          CONTENTFUL_DELIVERY_API_KEY: ${{ secrets.CONTENTFUL_DELIVERY_API_KEY }}
          CONTENTFUL_PREVIEW_API_KEY: ${{ secrets.CONTENTFUL_PREVIEW_API_KEY }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        run: docker compose -f infrastructure/docker/docker-compose.yml up -d

      - name: Install dependencies
        working-directory: ./src/e2e/CareLeavers.E2ETests
        run: yarn install

      - name: Install Playwright Browsers
        working-directory: ./src/e2e/CareLeavers.E2ETests
        run: yarn playwright install --with-deps

      - name: Run Playwright Tests
        working-directory: ./src/e2e/CareLeavers.E2ETests
        run: yarn playwright test -c playwright-ci.config.ts
